server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: mpecel
    password: mpecel_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
      #hibernate:
      #ddl-auto: update # Uncomment if needed
      #show-sql: true # Uncomment if needed
      #properties:
      #hibernate:
      #dialect: org.hibernate.dialect.PostgreSQLDialect

      #logging:
      #level:
      #org.hibernate.SQL: DEBUG
      #org.hibernate.type.descriptor.sql.BasicBinder: TRACE

      #crypto:
      #queries: bitcoin,ethereum,solana,cardano,xrp,chainlink,polkadot,dogecoin,kaspa,bonk,decentraland,dogeverse,sealana,99Bitcoins,eTukTuk,slothana,bendog,tamadoge

      #api:
      #newsapi:
      #url:
    #base: https://newsapi.org/v2/everything
    #key: ${API_NEWSAPI_KEY}
    #domains: cnn.com,nytimes.com,washingtonpost.com,usatoday.com,abcnews.go.com,aljazeera.com,arstechnica.com,apnews.com,axios.com,bleacherreport.com,bloomberg.com,breitbart.com,businessinsider.com,buzzfeed.com,cbsnews.com,us.cnn.com,cnnespanol.cnn.com,ccn.com,engadget.com,ew.com,espn.com,espncricinfo.com,fortune.com,foxnews.com,foxsports.com,news.google.com,news.ycombinator.com,ign.com,mashable.com,medicalnewstoday.com,msnbc.com,mtv.com/news,news.nationalgeographic.com,nationalreview.com,nbcnews.com,newscientist.com/sectio,n/news,newsweek.com,nymag.com,nextbigfuture.com,nfl.com/news,nhl.com/news,politico.com,polygon.com,recode.net,www.reddit.com/r/all,reuters.com,techcrunch.com,techradar.com,theamericanconservative.com,thehill.com,huffingtonpost.com,thenextweb.com,theverge.com,wsj.com,washingtonpost.com,washingtontimes.com,time.com,usatoday.com/news,news.vice.com,www.wired.com
